// <auto-generated />
using Foods_CompShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Foods_CompShop.Migrations
{
    [DbContext(typeof(Foods_CompShopContext))]
    [Migration("20200610212353_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Foods_CompShop.Models.CompShop", b =>
                {
                    b.Property<int>("CompShopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BJsAddtnPrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BJsConvPrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BJsShelfPrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BJsShoppedURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BJsShoppedZip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyerComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyerNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dept")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FutureSellDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FutureSellPrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IMU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LowestComp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MAC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaxPrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewPrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewSell")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PulledDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SamsAddtnPrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SamsConvPrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SamsShelfPrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SamsShoppedURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SamsShoppedZip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sell")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WHSE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompShopId");

                    b.ToTable("CompShop");
                });
#pragma warning restore 612, 618
        }
    }
}
